"use client";

import { createContext, useContext } from "react";

export type Locale = "zh" | "en";

const translations: Record<Locale, Record<string, string>> = {
  zh: {
    skip: "跳到工作区", practice: "把英语说清楚", research: "研究工作台", researchTool: "研究工具", backToPractice: "返回练习", example: "看看示例", loading: "载入中…",
    speak: "说一段", focus: "看重点", retry: "重说与对比", flow: "练习流程", newPractice: "开始新练习", export: "导出共评 JSON", practiceFooter: "一次只练一个重点，保留你自己的表达方式。",
    captureEyebrow: "下一次更清楚的沟通", captureTitle: "下一次工作沟通，从这里练起。", captureBody: "说说进展、遇到的阻塞，或你需要的帮助。", captureDuration: "30 秒也可以，最长 3 分钟。我们一起找出最值得改的一处。",
    context: "补充这次想表达的重点", optional: "可选", contextQuestion: "你希望对方记住什么？", contextPlaceholder: "例如：项目已完成，但需要对方确认上线日期。", upload: "上传音频", analyze: "看看哪里可以更清楚", analyzing: "正在听你的表达…", analyzingHelp: "正在转写并分析，较长的录音需要更多时间。请保留此页面。", readyHelp: "可以先回听，也可以直接查看建议。", privacy: "仅录制你自己的声音。音频会发送至 Gemini 和 ElevenLabs 处理，仅在当前会话临时使用，不写入工作台磁盘。", prompt: "不知道说什么？试试这个提示", promptBody: "想象同事问你：“How is your project going?”\n说说你完成了什么、现在卡在哪里，以及希望对方做什么。",
    reviewEyebrow: "一次只练一个重点", reviewUnusable: "先换一段更清楚的录音", reviewTitle: "先把这一处说清楚。", reviewClear: "这次没有发现明显的理解障碍。", recordAgain: "重新录一段", noFriction: "不用为了练习而刻意修改。你可以回听，再带着这次的表达去沟通。", finishNew: "完成，开始新练习", originalExcerpt: "听听你的原句", more: "还有 {count} 处可以留意", fullTranscript: "查看完整转写与录音", fullAudio: "完整录音",
    top: "重点", candidate: "候选", highEvidence: "高证据", mediumEvidence: "中证据", listenerEffect: "听者可能在哪里费力", clearerVersion: "一种更清楚的表达", suggestionNote: "不是唯一正确答案，也不要求消除口音。", practiceThis: "练这一句", reference: "听参考表达", generating: "生成中…", referenceAudio: "参考表达音频", humanVerdict: "真人对该候选的判断", pending: "待评", agree: "同意", partial: "部分同意", disagree: "不同意", evidenceNote: "证据备注", evidencePlaceholder: "写下听者实际听成什么或为何不同意",
    retryEyebrow: "再试一次", retryTitle: "用你自己的方式，再说一次。", retryBody: "只练下面这一处。回听原句和重说，自己决定要保留什么。", canRecord: "可以录制重说", demoNoAudio: "演示结果不含原始音频", missingAudio: "缺少原始音频", waiting: "等待原始分析", target: "练习目标", noTarget: "尚未选择摩擦点", targetHelp: "分析完成后默认选择重点，也可以从反馈卡中切换。", original: "原句", suggestedRetry: "建议重说版本", recordRetry: "录制重说片段", recordRetryHelp: "只重说当前目标，不必重录整段。", retryHint: "建议 5–20 秒，最长 40 秒", compare: "看看这次是否更清楚", comparing: "正在比较两个版本…", originalEffort: "原版 · 费力度", retryEffort: "重说版 · 费力度", effortHelp: "听者理解这段表达所需的努力，越低越轻松", judgeNote: "比较的是选中原句和本次重说。AI 判断供练习参考。此结果不替代真人盲评。", thisTry: "这次的表达", completeTitle: "这次练习完成了。", completeBody: "回听两个版本。想再试试，可以重新录音。", complete: "完成练习",
    testMethod: "测试方式", quick: "快速体验", quickDescription: "录音即可，适合检查流程和反馈质量", researchMode: "研究模式", researchDescription: "填写三项基准，适合测量意图复述率", oneLineGoal: "一句话目标", quickCaveat: "留空时只评估录音本身的听者费力，不能据此证明预定意图是否被准确传达。", groundTruth: "三项是研究测量的 ground truth，不用于评价工作内容。", progress: "进展", blocker: "阻塞", request: "请求", required: "必填",
    coachOutput: "教练反馈", noAnalysis: "没有分析结果", noAnalysisBody: "返回第一步提交音频，或点击页面右上角的“看看示例”。", waitingAnalysis: "等待分析结果", abandon: "应放弃", unsuitable: "当前录音不适合强判断", analyzable: "可分析", found: "发现 {count} 个高影响候选", transcriptEvidence: "转写与时间证据", languageSignal: "语言信号", noTranscript: "暂无转写。", timeline: "词级时间轴", noEvidence: "未发现高证据摩擦", noEvidenceBody: "证据不足时系统不会制造纠正。真人仍可记录独立判断。", independentReview: "真人独立评测", independentReviewBody: "先复述，再查看模型结论。", recall: "一次收听后的意图复述", clear: "清楚", missing: "缺失", overallEffort: "整体听者费力度", easy: "1 容易", difficult: "5 费力", topMoment: "你认为最影响理解的时刻", topMomentPlaceholder: "写下时间点、听成了什么或需要回推什么", notes: "评测备注", notesPlaceholder: "只记录与理解任务有关的证据", humanPending: "真人待评",
    notSelected: "尚未选择音频", startRecording: "开始录音", stopRecording: "停止录音", reRecord: "重新录音", remove: "移除", preview: "预览", recording: "正在录音…", ready: "已就绪", currentSession: "仅当前会话", longest: "最长 {seconds} 秒，点击停止完成", audioTooLarge: "音频不能超过 {mb} MB", invalidAudio: "请选择音频文件", emptyAudio: "音频为空或过短", unsupportedRecording: "当前浏览器不支持录音，请改用上传音频", cannotStart: "无法开始录音", cannotRead: "无法读取音频", invalidRecording: "录音无效",
    checking: "检查中", configured: "已配置", setupNeeded: "待配置", serviceStatus: "服务状态", demoSession: "演示", session: "会话", noSession: "未创建会话", cleared: "当前会话已从浏览器内存清除。", analysisDone: "分析完成，先从最值得改的一处开始。", demoLoaded: "这是示例反馈，不含原始录音。开始新练习即可体验真实回听和重说对比。", comparisonDone: "对比完成。回听两个版本，感受这次表达的变化。", exported: "共评结果已导出；JSON 不包含音频字节或 API 密钥。"
  },
  en: {
    skip: "Skip to workspace", practice: "Speak English clearly", research: "Research workbench", researchTool: "Research tools", backToPractice: "Back to practice", example: "View example", loading: "Loading…",
    speak: "Speak", focus: "Review", retry: "Retry & compare", flow: "Practice flow", newPractice: "Start a new practice", export: "Export review JSON", practiceFooter: "Work on one point at a time while keeping your own voice.",
    captureEyebrow: "Your next clearer conversation", captureTitle: "Start with your next work conversation.", captureBody: "Share your progress, a blocker, or the help you need.", captureDuration: "Thirty seconds is enough; record up to three minutes. We’ll find one thing worth improving.",
    context: "Add the point you want to make", optional: "Optional", contextQuestion: "What do you want your listener to remember?", contextPlaceholder: "For example: The project is complete, but I need confirmation of the launch date.", upload: "Upload audio", analyze: "See what could be clearer", analyzing: "Listening to your message…", analyzingHelp: "We’re transcribing and reviewing your audio. Longer recordings may take more time; please keep this page open.", readyHelp: "You can listen back first or view the suggestion now.", privacy: "Record only your own voice. Audio is processed by Gemini and ElevenLabs for this session only and is never written to this workbench’s disk.", prompt: "Not sure what to say? Try this prompt", promptBody: "Imagine a teammate asks: “How is your project going?”\nSay what you’ve finished, where you’re blocked, and what you need next.",
    reviewEyebrow: "One thing at a time", reviewUnusable: "Try a clearer recording first", reviewTitle: "Start by making this one part clear.", reviewClear: "No clear comprehension issue appeared this time.", recordAgain: "Record again", noFriction: "You do not need to change your message just to practise. Listen back, then take this version into your conversation.", finishNew: "Finish and start a new practice", originalExcerpt: "Listen to your original words", more: "There are {count} more points to notice", fullTranscript: "View full transcript and recording", fullAudio: "Full recording",
    top: "Focus", candidate: "Candidate", highEvidence: "High evidence", mediumEvidence: "Medium evidence", listenerEffect: "Where a listener may have to work", clearerVersion: "One clearer way to say it", suggestionNote: "This is not the only right answer, and it does not ask you to erase your accent.", practiceThis: "Practise this line", reference: "Listen to a reference", generating: "Generating…", referenceAudio: "Reference expression audio", humanVerdict: "Human verdict on this candidate", pending: "Pending", agree: "Agree", partial: "Partly agree", disagree: "Disagree", evidenceNote: "Evidence note", evidencePlaceholder: "What did the listener hear, or why do you disagree?",
    retryEyebrow: "Try again", retryTitle: "Say it again, in your own way.", retryBody: "Practise only this part. Listen to the original and your retry, then decide what to keep.", canRecord: "Ready to record a retry", demoNoAudio: "The example has no original audio", missingAudio: "Original audio is missing", waiting: "Waiting for original analysis", target: "Practice target", noTarget: "No friction point selected", targetHelp: "After analysis, the focus point is selected by default; choose another one from the feedback card if needed.", original: "Original excerpt", suggestedRetry: "Suggested retry", recordRetry: "Record your retry", recordRetryHelp: "Say only the current target; you do not need to record the whole update again.", retryHint: "Aim for 5–20 seconds; up to 40 seconds", compare: "See if this is clearer", comparing: "Comparing both versions…", originalEffort: "Original · effort", retryEffort: "Retry · effort", effortHelp: "Lower effort means the listener needs less work to understand this part.", judgeNote: "The comparison uses the selected original excerpt and this retry. The AI result is a practice signal and does not replace a human blind review.", thisTry: "This retry", completeTitle: "This practice is complete.", completeBody: "Listen to both versions. You can record again if you want another try.", complete: "Finish practice",
    testMethod: "Test method", quick: "Quick practice", quickDescription: "Record right away to check the flow and feedback quality", researchMode: "Research mode", researchDescription: "Set three references to measure one-listen recall", oneLineGoal: "One-line goal", quickCaveat: "Without a declared goal, we only assess listener effort in the recording; it cannot prove that a particular intent was conveyed.", groundTruth: "These three fields are research ground truth, not an evaluation of the work itself.", progress: "Progress", blocker: "Blocker", request: "Request", required: "Required",
    coachOutput: "Coach output", noAnalysis: "No analysis yet", noAnalysisBody: "Return to the first step to submit audio, or use “View example” in the top right.", waitingAnalysis: "Waiting for analysis", abandon: "Do not use", unsuitable: "This recording is not suitable for a strong judgment", analyzable: "Ready to analyse", found: "{count} high-impact candidates found", transcriptEvidence: "Transcript and time evidence", languageSignal: "Language signal", noTranscript: "No transcript yet.", timeline: "Word-level timeline", noEvidence: "No high-evidence friction found", noEvidenceBody: "When evidence is weak, the system does not invent corrections. A human reviewer can still record an independent assessment.", independentReview: "Independent human review", independentReviewBody: "Recall first, then view the model’s conclusion.", recall: "Intent recall after one listen", clear: "Clear", missing: "Missing", overallEffort: "Overall listener effort", easy: "1 Easy", difficult: "5 Effortful", topMoment: "Moment that most affected understanding", topMomentPlaceholder: "Note the time, what the listener heard, or what they had to infer", notes: "Reviewer notes", notesPlaceholder: "Record evidence relevant to understanding only", humanPending: "Human pending",
    notSelected: "No audio selected", startRecording: "Start recording", stopRecording: "Stop recording", reRecord: "Record again", remove: "Remove", preview: "Preview", recording: "Recording…", ready: "Ready", currentSession: "This session only", longest: "Up to {seconds} seconds; click stop when you are done", audioTooLarge: "Audio must be no larger than {mb} MB", invalidAudio: "Choose an audio file", emptyAudio: "The audio is empty or too short", unsupportedRecording: "This browser cannot record audio; upload an audio file instead", cannotStart: "Could not start recording", cannotRead: "Could not read audio", invalidRecording: "Invalid recording",
    checking: "Checking", configured: "Configured", setupNeeded: "Setup needed", serviceStatus: "Service status", demoSession: "Example", session: "Session", noSession: "No session created", cleared: "The current session has been cleared from browser memory.", analysisDone: "Analysis is ready. Start with the one point worth improving most.", demoLoaded: "This is example feedback without original audio. Start a new practice to try real playback and comparison.", comparisonDone: "Comparison complete. Listen to both versions and notice what changed.", exported: "Review results exported; the JSON does not include audio bytes or API keys."
  },
};

interface LocaleValue { locale: Locale; setLocale: (locale: Locale) => void; c: Record<string, string>; }
export const LocaleContext = createContext<LocaleValue>({ locale: "zh", setLocale: () => {}, c: translations.zh });
export const useLocale = () => useContext(LocaleContext);
export const getCopy = (locale: Locale) => translations[locale];
export const interpolate = (value: string, variables: Record<string, string | number>) => value.replace(/\{(\w+)\}/g, (_, key) => String(variables[key] ?? ""));
