import { providerVersions } from "@/lib/providers";
import type { RuntimeConfig, WorkbenchSession } from "@/lib/types";

export function createDemoSession(config: RuntimeConfig): WorkbenchSession {
  return {
    session_id: "demo-session",
    created_at: new Date().toISOString(),
    demo: true,
    intent: {
      takeaway: "Please confirm the launch date today.",
    },
    transcript: {
      text: "The payment page is finished. The security review, I sent it on Thursday but maybe the result is not yet, so if possible today the launch date, can you confirm?",
      language_code: "eng",
      language_probability: 0.98,
      words: [
        { text: "The", start: 0.1, end: 0.28, type: "word", logprob: -0.03 },
        { text: "payment", start: 0.29, end: 0.72, type: "word", logprob: -0.05 },
        { text: "page", start: 0.73, end: 1.04, type: "word", logprob: -0.04 },
        { text: "is", start: 1.05, end: 1.18, type: "word", logprob: -0.02 },
        { text: "finished", start: 1.19, end: 1.68, type: "word", logprob: -0.05 },
        { text: "The", start: 2.0, end: 2.12, type: "word", logprob: -0.04 },
        { text: "security", start: 2.15, end: 2.6, type: "word", logprob: -0.12 },
        { text: "review", start: 2.61, end: 3.1, type: "word", logprob: -0.11 },
        { text: "I", start: 3.3, end: 3.42, type: "word", logprob: -0.05 },
        { text: "sent", start: 3.43, end: 3.7, type: "word", logprob: -0.08 },
        { text: "it", start: 3.71, end: 3.85, type: "word", logprob: -0.09 },
        { text: "on", start: 3.86, end: 4.0, type: "word", logprob: -0.03 },
        { text: "Thursday", start: 4.01, end: 4.5, type: "word", logprob: -0.11 },
        { text: "but", start: 4.7, end: 4.85, type: "word", logprob: -0.06 },
        { text: "maybe", start: 4.86, end: 5.15, type: "word", logprob: -0.14 },
        { text: "the", start: 5.16, end: 5.28, type: "word", logprob: -0.04 },
        { text: "result", start: 5.29, end: 5.7, type: "word", logprob: -0.18 },
        { text: "is", start: 5.71, end: 5.85, type: "word", logprob: -0.05 },
        { text: "not", start: 5.86, end: 6.05, type: "word", logprob: -0.1 },
        { text: "yet", start: 6.06, end: 6.4, type: "word", logprob: -0.24 },
        { text: "so", start: 6.6, end: 6.75, type: "word", logprob: -0.07 },
        { text: "if", start: 6.8, end: 6.95, type: "word", logprob: -0.08 },
        { text: "possible", start: 6.96, end: 7.4, type: "word", logprob: -0.13 },
        { text: "today", start: 7.41, end: 8.0, type: "word", logprob: -0.09 },
        { text: "the", start: 8.05, end: 8.18, type: "word", logprob: -0.04 },
        { text: "launch", start: 8.19, end: 8.55, type: "word", logprob: -0.08 },
        { text: "date", start: 8.56, end: 9.0, type: "word", logprob: -0.09 },
        { text: "can", start: 9.1, end: 9.3, type: "word", logprob: -0.06 },
        { text: "you", start: 9.31, end: 9.5, type: "word", logprob: -0.04 },
        { text: "confirm", start: 9.51, end: 10.2, type: "word", logprob: -0.08 },
      ],
    },
    coach: {
      quality: { usable: true, reason: "ok", note: "单人英语清晰，可进行任务级分析。" },
      summary: "进展容易听懂；阻塞状态和请求出现得较晚，需要听者回推句子关系。",
      frictions: [
        {
          id: "friction-1",
          start_word_index: 13,
          end_word_index: 26,
          focus: "organization",
          impact: "comprehension",
          start_sec: 4.7,
          end_sec: 9,
          category: "processing",
          intent_slot: "overall",
          original_excerpt: "but maybe the result is not yet, so if possible today the launch date",
          listener_effect: "听者需要先判断“it”和“result”分别指什么，直到句尾才知道你在等待安全审查结果。",
          observation: "阻塞和请求挤在同一长句里，指代到句尾才清楚。",
          practice_cue: "先说出还在等安全审查，再单独提出确认上线日期。",
          evidence_sources: ["audio", "text", "timing", "context"],
          evidence_level: "high",
          suggested_version: "The payment page is finished, but the security review is still pending. Please confirm the launch date today.",
          optional_style_only: false,
        },
      ],
    },
    versions: providerVersions(config),
  };
}
